import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import type { Plugin } from 'vite';

/**
 * Extract early paint tokens from the site theme: `:root` blocks (including
 * those nested in `prefers-color-scheme` media) and top-level `body { ... }`.
 */
export function extractCriticalTheme(css: string): string {
	const chunks: string[] = [];

	// Prefer `:root:root` (higher specificity site tokens) when present.
	for (const m of css.matchAll(/:root(?::root)?\s*\{[^}]*\}/g)) {
		chunks.push(m[0]);
	}

	for (const m of css.matchAll(
		/@media\s*\([^)]*prefers-color-scheme[^)]*\)\s*\{\s*:root(?::root)?\s*\{[^}]*\}\s*\}/g
	)) {
		chunks.push(m[0]);
	}

	for (const m of css.matchAll(/(?:^|\n)(?:html\s+)?body\s*\{[^}]*\}/g)) {
		chunks.push(m[0].trim());
	}

	return chunks.join('\n');
}

export function writeCriticalThemeModule(siteThemePath: string, outPath: string): string {
	let css = '';
	if (existsSync(siteThemePath)) {
		try {
			css = readFileSync(siteThemePath, 'utf8');
		} catch {
			css = '';
		}
	}
	const critical = extractCriticalTheme(css);
	const source = `/** Auto-generated by downpress — do not edit. */\nexport default ${JSON.stringify(critical)};\n`;
	writeFileSync(outPath, source, 'utf8');
	return critical;
}

/**
 * Keep `$lib/critical-theme.generated.ts` in sync with the site theme so
 * layout can inline tokens without a Vite virtual module (SSR-safe).
 */
export function criticalThemePlugin(siteThemePath: string, outPath: string): Plugin {
	return {
		name: 'downpress-critical-theme',
		buildStart() {
			writeCriticalThemeModule(siteThemePath, outPath);
		},
		configureServer(server) {
			writeCriticalThemeModule(siteThemePath, outPath);
			server.watcher.add(siteThemePath);
			server.watcher.on('change', (file) => {
				const a = file.replace(/\\/g, '/');
				const b = siteThemePath.replace(/\\/g, '/');
				if (a !== b) return;
				writeCriticalThemeModule(siteThemePath, outPath);
				const mod = server.moduleGraph.getModuleById(outPath);
				if (mod) {
					server.moduleGraph.invalidateModule(mod);
					server.ws.send({ type: 'full-reload' });
				}
			});
		}
	};
}
