import type { DesignBrief } from './ir.ts';

const DEFAULT_BRIEF: DesignBrief = {
	mood: 'Quiet editorial personal site with a modern accent.',
	do: ['Keep reading measure comfortable', 'Use a single clear accent', 'Prefer whitespace over cards'],
	dont: ['Do not add marketing section grids', 'Do not introduce pill-stat strips'],
	tokens: {
		accent: '#1e4d6b',
		accentStrong: '#163a52',
		bg: '#f7f5f1',
		ink: '#1a1917'
	},
	density: 'sparse',
	cssNotes: []
};

/** Minimal token theme — code-owned template, LLM only supplies tokens. */
export function themeCssFromBrief(brief: DesignBrief = DEFAULT_BRIEF): string {
	const t = { ...DEFAULT_BRIEF.tokens, ...brief.tokens };
	const density =
		brief.density === 'dense'
			? `body { font-size: 1.1rem; line-height: 1.65; }\n.wrap { --gap: clamp(1rem, 3vw, 1.75rem); }`
			: brief.density === 'balanced'
				? `body { font-size: 1.15rem; }`
				: `body { font-size: 1.2rem; line-height: 1.75; }`;

	return `/* Generated by downpress import — edit freely.
 * Mood: ${brief.mood.replace(/\*\//g, '')}
 */
:root {
	--accent: ${t.accent};
	--accent-strong: ${t.accentStrong};
	--accent-wash: color-mix(in srgb, var(--accent) 7%, transparent);
${t.bg ? `\t--bg: ${t.bg};` : ''}
${t.ink ? `\t--ink: ${t.ink};` : ''}
${t.inkSoft ? `\t--ink-soft: ${t.inkSoft};` : ''}
}

@media (prefers-color-scheme: dark) {
	:root {
		--accent: ${lighten(t.accent)};
		--accent-strong: ${lighten(t.accentStrong)};
	}
}

${density}

.site-header {
	border-bottom-color: color-mix(in srgb, var(--accent) 25%, var(--rule));
}

.post-title,
.page-header h1,
.post-header h1 {
	letter-spacing: -0.025em;
}
`;
}

function lighten(hex: string): string {
	// Soft fallback accents for dark mode when LLM only gave light-theme hexes.
	if (!/^#[0-9a-fA-F]{6}$/.test(hex)) return '#8eb6d4';
	const n = parseInt(hex.slice(1), 16);
	const r = Math.min(255, ((n >> 16) & 255) + 60);
	const g = Math.min(255, ((n >> 8) & 255) + 60);
	const b = Math.min(255, (n & 255) + 60);
	return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, '0')}`;
}

export function parseBriefJson(raw: string): DesignBrief {
	const start = raw.indexOf('{');
	const end = raw.lastIndexOf('}');
	if (start === -1 || end === -1) throw new Error('No JSON object in model response');
	const data = JSON.parse(raw.slice(start, end + 1)) as Partial<DesignBrief>;
	if (!data.tokens?.accent || !data.tokens?.accentStrong) {
		throw new Error('Design brief missing tokens.accent / tokens.accentStrong');
	}
	return {
		mood: String(data.mood ?? DEFAULT_BRIEF.mood),
		do: Array.isArray(data.do) ? data.do.map(String) : DEFAULT_BRIEF.do,
		dont: Array.isArray(data.dont) ? data.dont.map(String) : DEFAULT_BRIEF.dont,
		tokens: {
			accent: String(data.tokens.accent),
			accentStrong: String(data.tokens.accentStrong),
			bg: data.tokens.bg ? String(data.tokens.bg) : undefined,
			ink: data.tokens.ink ? String(data.tokens.ink) : undefined,
			inkSoft: data.tokens.inkSoft ? String(data.tokens.inkSoft) : undefined
		},
		density:
			data.density === 'dense' || data.density === 'balanced' || data.density === 'sparse'
				? data.density
				: 'sparse',
		cssNotes: Array.isArray(data.cssNotes) ? data.cssNotes.map(String) : []
	};
}

/** Extract CSS custom properties from inline :root blocks (source site). */
export function tokensFromSourceCss(html: string): Partial<DesignBrief['tokens']> {
	const m = html.match(/:root\s*\{([^}]+)\}/);
	if (!m) return {};
	const block = m[1];
	const vars = new Map<string, string>();
	for (const hit of block.matchAll(/--([a-zA-Z0-9-_]+)\s*:\s*([^;}]+)/g)) {
		vars.set(hit[1], hit[2].trim());
	}
	const resolve = (name: string, depth = 0): string | undefined => {
		if (depth > 5) return undefined;
		const raw = vars.get(name);
		if (!raw) return undefined;
		const ref = raw.match(/^var\(\s*--([a-zA-Z0-9-_]+)\s*\)$/);
		if (ref) return resolve(ref[1], depth + 1);
		return raw;
	};
	const firstHex = (...names: string[]) => {
		for (const n of names) {
			const v = resolve(n);
			if (v && /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(v)) return v;
		}
		return undefined;
	};
	const accent = firstHex('accent-color', 'accent', 'color-gold', 'color-augment');
	const bg = firstHex('bg-color', 'bg', 'color-bg', 'color-cream');
	const ink = firstHex('text-color', 'ink', 'color-espresso');
	const out: Partial<DesignBrief['tokens']> = {};
	if (accent) {
		out.accent = accent;
		out.accentStrong = firstHex('accent-strong', 'color-understand') || accent;
	}
	if (bg) out.bg = bg;
	if (ink) out.ink = ink;
	return out;
}

export { DEFAULT_BRIEF };
